name = "statusmap"
compatibility_date = "2022-02-17"
type = "javascript"
account_id = "864cdf76f8254fb5539425299984d766"
zone_id = "3c64a34e26b07a72bd3d3d3172d4c631"
route = "https://statusmap.cloudflare.community/*"

kv_namespaces = [
  { binding = "KV", id = "b67bf7eb75f64392b0c3d7fef8e63079", preview_id = "b67bf7eb75f64392b0c3d7fef8e63079" }
]

[build]
command = "pnpm run build"
watch_dir = "src"
[build.upload]
format = "modules"
main = "./index.mjs"
[miniflare]
port = 80
watch = true